### ISSUE TITLE
1

### ISSUE THREAD

**Issue by DmitryThink** [Warble98/JavaCwiczenia#1]
public class CW13 {
	public static void main(String[] args) {
		kwa(5, 'o');
	}
	public static void kwa(int x, char o){
		for (int i = 0; i < x*x; i++) {
			if(i%x==0){
				System.out.println();
			}
			if(i%2==0){
				System.out.print(o + " ");
			}else System.out.print('x' + " ");
			
		}
	}
}

**Comment by Warble98** [comment]
Повністю погоджуюсь з твоїм рішенням , я просто хотів зробити через двовимірний масив.
